export default {
  brand: '春联',
  brandFull: '春联 · 传世名家楹联与金墨名帖定制',
  seo: {
    title: '春联 · 传世名家手写与烫金春联定制平台 | 喜迎新春',
    description: '春联网专注于传世名家手写对联、烫金企业门联与创意新春楹联定制。采用特级万年红宣纸与耐候金墨，让每一副春联都承载吉祥安康与传承之美。',
    ogTitle: '春联 · 传世名家手写与烫金春联定制平台',
    ogDescription: '传世名家手写对联，烫金企业门联与创意新春楹联定制。',
    keywords: '春联定制, 手写春联, 烫金对联, 万年红宣纸, 名家书法, 新春楹联, 企业门联, 蛇年春联',
  },
  nav: [
    { label: '首页', to: '/' },
    { label: '全部春联', to: '/search' },
    { label: '手写真迹', to: '/search?type=手写春联' },
    { label: '烫金门联', to: '/search?type=烫金春联' },
    { label: '企业定制', to: '/search?type=企业春联' },
    { label: '联系我们', to: '/contact' },
  ],
  hero: {
    tagline: '乙巳蛇年 · 迎春纳福',
    title: '笔墨千秋 翰墨凝香',
    subtitle: '福泽万家 岁岁平安',
    desc: '名家手写 · 万年红宣 · 耐候金墨。每一副春联均由当代书法名家倾情挥毫，匠心传承，历经风雨仍熠熠生辉。',
    cta: '选购新春佳联',
    secondaryCta: '定制企业大联',
    coupletLeft: '迎喜迎春迎富贵',
    coupletRight: '接财接福接平安',
    coupletCenter: '吉星高照',
  },
  presets: [
    { name: '新春吉祥', left: '迎喜迎春迎富贵', right: '接财接福接平安', center: '吉星高照' },
    { name: '宏图大展', left: '大展宏图兴骏业', right: '顺心如意顺春风', center: '万事如意' },
    { name: '阖家安康', left: '和顺门第增百福', right: '合家欢乐纳千祥', center: '福满人间' },
    { name: '财源广进', left: '门迎晓日财源广', right: '户纳春风吉庆多', center: '迎春接福' },
  ],
  categories: [
    { name: '手写真迹', slug: '手写春联', desc: '书法名家亲笔真迹，笔力遒劲，独一无二', image: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&w=800&q=80', badge: '大师手笔' },
    { name: '烫金门联', slug: '烫金春联', desc: '24K金箔重彩压烫，金碧辉煌，大气磅礴', image: 'https://images.unsplash.com/photo-1610375461246-83df859d849d?auto=format&fit=crop&w=800&q=80', badge: '热销推荐' },
    { name: '万年红宣', slug: '万年红宣', desc: '传统手工特级万年红，5年不褪色', image: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?auto=format&fit=crop&w=800&q=80', badge: '非遗工艺' },
    { name: '企业定制', slug: '企业春联', desc: '企业门头专属对联，量体裁衣，彰显气派', image: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=800&q=80', badge: '高端尊享' },
    { name: '创意楹联', slug: '创意春联', desc: '国潮雅趣，新中式艺术对联盒套装', image: 'https://images.unsplash.com/photo-1578926375605-eaf7559b1458?auto=format&fit=crop&w=800&q=80', badge: '国潮礼盒' },
  ],
  features: [
    { title: '特级万年红宣纸', desc: '源自安徽泾县非遗工坊，经古法浸染，历经数年风吹日晒依然鲜艳如初。', icon: 'paper', tag: '非遗材质' },
    { title: '耐候沉金墨宝', desc: '进口哑光金粉配比研磨，字迹饱满附着力强，日光下熠熠生辉不掉粉。', icon: 'ink', tag: '独门金墨' },
    { title: '当代名家挥毫', desc: '中国书法家协会会员亲笔泼墨，每一字皆蕴含气韵与功力，具极高观赏值。', icon: 'brush', tag: '真迹保证' },
    { title: '礼盒级保护装裱', desc: '精美锦盒封装，内附防潮卷轴与贴联专用无痕胶，开箱即送即贴。', icon: 'frame', tag: '高端礼盒' },
  ],
  specs: [
    { label: '传承工艺', value: '120+', unit: '年历史' },
    { label: '合作书法名家', value: '68', unit: '位签约大师' },
    { label: '好评率', value: '99.8', unit: '%' },
    { label: '不褪色品质承诺', value: '5', unit: '年品质保固' },
  ],
  trustSignals: [
    { value: '50,000+', label: '家庭新春选择' },
    { value: '1,200+', label: '企业门联定制' },
    { value: '4.98', label: '综合好评得分' },
    { value: '24h', label: '加急发货服务' },
  ],
  newsletter: {
    tag: '新春特惠预告',
    title: '预订乙巳蛇年新春第一福',
    desc: '订阅我们的新春楹联通讯，即刻获取名家新春限量真迹上架通知及85折首单特惠礼券。',
    placeholder: '请输入您的电子邮箱地址...',
    cta: '即刻领取新春福礼',
  },
  footer: {
    desc: '传世名家手写对联，烫金企业门联与创意新春楹联定制平台。继承非遗书法脉络，把新春第一份吉祥带回万家。',
    cols: [
      { title: '春联品类', links: [{ label: '手写真迹', to: '/search?type=手写春联' }, { label: '烫金门联', to: '/search?type=烫金春联' }, { label: '企业大联', to: '/search?type=企业春联' }, { label: '国潮礼盒', to: '/search?type=创意春联' }] },
      { title: '服务支持', links: [{ label: '定制说明', to: '/contact' }, { label: '包装与配送', to: '/contact' }, { label: '张贴指南', to: '/contact' }, { label: '售后保固', to: '/contact' }] },
      { title: '关于我们', links: [{ label: '名家阵容', to: '/contact' }, { label: '非遗宣纸工坊', to: '/contact' }, { label: '企业合作', to: '/contact' }] },
    ],
  },
}
