
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T

interface _GlobalComponents {
  'LayoutPageContent': typeof import("../../../../../../components/layouts/Page/Content.vue").default
  'LayoutPageFooter': typeof import("../../../../../../components/layouts/Page/Footer.vue").default
  'LayoutPageHeader': typeof import("../../../../../../components/layouts/Page/Header.vue").default
  'LayoutPageNavbarDropdownThemeSwitcher': typeof import("../../../../../../components/layouts/Page/NavbarDropdown/ThemeSwitcher.vue").default
  'LayoutPageNavbarMenuItem': typeof import("../../../../../../components/layouts/Page/NavbarMenu/Item.vue").default
  'LayoutPageNavbarMenuWrapper': typeof import("../../../../../../components/layouts/Page/NavbarMenu/Wrapper.vue").default
  'LayoutPageSectionTitle': typeof import("../../../../../../components/layouts/Page/Section/Title.vue").default
  'LayoutPageSection': typeof import("../../../../../../components/layouts/Page/Section/index.vue").default
  'LayoutPageTitle': typeof import("../../../../../../components/layouts/Page/Title.vue").default
  'LayoutPageWrapper': typeof import("../../../../../../components/layouts/Page/Wrapper.vue").default
  'AwesomeActionSheetGroup': typeof import("../../../../../../components/awesome/ActionSheet/Group.vue").default
  'AwesomeActionSheetHeader': typeof import("../../../../../../components/awesome/ActionSheet/Header.vue").default
  'AwesomeActionSheetHeaderMessage': typeof import("../../../../../../components/awesome/ActionSheet/HeaderMessage.vue").default
  'AwesomeActionSheetHeaderTitle': typeof import("../../../../../../components/awesome/ActionSheet/HeaderTitle.vue").default
  'AwesomeActionSheetItem': typeof import("../../../../../../components/awesome/ActionSheet/Item.vue").default
  'AwesomeActionSheetItemButton': typeof import("../../../../../../components/awesome/ActionSheet/ItemButton.vue").default
  'AwesomeActionSheet': typeof import("../../../../../../components/awesome/ActionSheet/index.vue").default
  'AwesomeAlertBanner': typeof import("../../../../../../components/awesome/AlertBanner.vue").default
  'AwesomeButton': typeof import("../../../../../../components/awesome/Button/index.vue").default
  'AwesomeCardContent': typeof import("../../../../../../components/awesome/Card/Content.vue").default
  'AwesomeCardFooter': typeof import("../../../../../../components/awesome/Card/Footer.vue").default
  'AwesomeCardTitle': typeof import("../../../../../../components/awesome/Card/Title.vue").default
  'AwesomeCard': typeof import("../../../../../../components/awesome/Card/index.vue").default
  'AwesomeContentDoc': typeof import("../../../../../../components/awesome/Content/Doc.vue").default
  'AwesomeContentRenderer': typeof import("../../../../../../components/awesome/Content/Renderer.vue").default
  'AwesomeFloatingMenu': typeof import("../../../../../../components/awesome/FloatingMenu.vue").default
  'AwesomeFormSwitch': typeof import("../../../../../../components/awesome/Form/Switch.vue").default
  'AwesomeFormTextInput': typeof import("../../../../../../components/awesome/Form/TextInput.vue").default
  'AwesomeLink': typeof import("../../../../../../components/awesome/Link/index.vue").default
  'AwesomeLoading': typeof import("../../../../../../components/awesome/Loading.vue").default
  'AwesomeTab': typeof import("../../../../../../components/awesome/Tab.vue").default
  'AwesomeTabs': typeof import("../../../../../../components/awesome/Tabs.vue").default
  'AwesomeToast': typeof import("../../../../../../components/awesome/Toast/index.vue").default
  'ContentDoc': typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue").default
  'ContentList': typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue").default
  'ContentNavigation': typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue").default
  'ContentQuery': typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue").default
  'ContentRenderer': typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue").default
  'ContentRendererMarkdown': typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue").default
  'ContentSlot': typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue").default
  'DocumentDrivenEmpty': typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue").default
  'DocumentDrivenNotFound': typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue").default
  'Markdown': typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue").default
  'ProseCode': typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue").default
  'ProseCodeInline': typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue").default
  'ProsePre': typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue").default
  'ProseA': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue").default
  'ProseBlockquote': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue").default
  'ProseEm': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue").default
  'ProseH1': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue").default
  'ProseH2': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue").default
  'ProseH3': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue").default
  'ProseH4': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue").default
  'ProseH5': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue").default
  'ProseH6': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue").default
  'ProseHr': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue").default
  'ProseImg': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue").default
  'ProseLi': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue").default
  'ProseOl': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue").default
  'ProseP': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue").default
  'ProseScript': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue").default
  'ProseStrong': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue").default
  'ProseTable': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue").default
  'ProseTbody': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue").default
  'ProseTd': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue").default
  'ProseTh': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue").default
  'ProseThead': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue").default
  'ProseTr': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue").default
  'ProseUl': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue").default
  'NuxtWelcome': typeof import("../../../../../../node_modules/nuxt/dist/app/components/welcome.vue").default
  'NuxtLayout': typeof import("../../../../../../node_modules/nuxt/dist/app/components/nuxt-layout").default
  'NuxtErrorBoundary': typeof import("../../../../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
  'ClientOnly': typeof import("../../../../../../node_modules/nuxt/dist/app/components/client-only").default
  'DevOnly': typeof import("../../../../../../node_modules/nuxt/dist/app/components/dev-only").default
  'ServerPlaceholder': typeof import("../../../../../../node_modules/nuxt/dist/app/components/server-placeholder").default
  'NuxtLink': typeof import("../../../../../../node_modules/nuxt/dist/app/components/nuxt-link").default
  'NuxtLoadingIndicator': typeof import("../../../../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
  'NuxtTime': typeof import("../../../../../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
  'NuxtRouteAnnouncer': typeof import("../../../../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
  'NuxtImg': typeof import("../../../../../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg
  'NuxtPicture': typeof import("../../../../../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture
  'HeadlessCombobox': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/combobox/combobox").Combobox
  'HeadlessComboboxLabel': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/combobox/combobox").ComboboxLabel
  'HeadlessComboboxButton': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/combobox/combobox").ComboboxButton
  'HeadlessComboboxInput': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/combobox/combobox").ComboboxInput
  'HeadlessComboboxOptions': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/combobox/combobox").ComboboxOptions
  'HeadlessComboboxOption': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/combobox/combobox").ComboboxOption
  'HeadlessDialog': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/dialog/dialog").Dialog
  'HeadlessDialogOverlay': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/dialog/dialog").DialogOverlay
  'HeadlessDialogBackdrop': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/dialog/dialog").DialogBackdrop
  'HeadlessDialogPanel': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/dialog/dialog").DialogPanel
  'HeadlessDialogTitle': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/dialog/dialog").DialogTitle
  'HeadlessDialogDescription': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/dialog/dialog").DialogDescription
  'HeadlessDisclosure': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/disclosure/disclosure").Disclosure
  'HeadlessDisclosureButton': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/disclosure/disclosure").DisclosureButton
  'HeadlessDisclosurePanel': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/disclosure/disclosure").DisclosurePanel
  'HeadlessFocusTrap': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/focus-trap/focus-trap").FocusTrap
  'HeadlessListbox': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/listbox/listbox").Listbox
  'HeadlessListboxLabel': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/listbox/listbox").ListboxLabel
  'HeadlessListboxButton': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/listbox/listbox").ListboxButton
  'HeadlessListboxOptions': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/listbox/listbox").ListboxOptions
  'HeadlessListboxOption': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/listbox/listbox").ListboxOption
  'HeadlessMenu': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/menu/menu").Menu
  'HeadlessMenuButton': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/menu/menu").MenuButton
  'HeadlessMenuItems': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/menu/menu").MenuItems
  'HeadlessMenuItem': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/menu/menu").MenuItem
  'HeadlessPopover': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/popover/popover").Popover
  'HeadlessPopoverButton': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/popover/popover").PopoverButton
  'HeadlessPopoverOverlay': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/popover/popover").PopoverOverlay
  'HeadlessPopoverPanel': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/popover/popover").PopoverPanel
  'HeadlessPopoverGroup': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/popover/popover").PopoverGroup
  'HeadlessPortal': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/portal/portal").Portal
  'HeadlessPortalGroup': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/portal/portal").PortalGroup
  'HeadlessRadioGroup': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/radio-group/radio-group").RadioGroup
  'HeadlessRadioGroupOption': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/radio-group/radio-group").RadioGroupOption
  'HeadlessRadioGroupLabel': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/radio-group/radio-group").RadioGroupLabel
  'HeadlessRadioGroupDescription': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/radio-group/radio-group").RadioGroupDescription
  'HeadlessSwitchGroup': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/switch/switch").SwitchGroup
  'HeadlessSwitch': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/switch/switch").Switch
  'HeadlessSwitchLabel': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/switch/switch").SwitchLabel
  'HeadlessSwitchDescription': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/switch/switch").SwitchDescription
  'HeadlessTabGroup': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/tabs/tabs").TabGroup
  'HeadlessTabList': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/tabs/tabs").TabList
  'HeadlessTab': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/tabs/tabs").Tab
  'HeadlessTabPanels': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/tabs/tabs").TabPanels
  'HeadlessTabPanel': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/tabs/tabs").TabPanel
  'HeadlessTransitionChild': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/transitions/transition").TransitionChild
  'HeadlessTransitionRoot': typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/transitions/transition").TransitionRoot
  'ColorScheme': typeof import("../../../../../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue").default
  'MDC': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue").default
  'MDCRenderer': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue").default
  'MDCSlot': typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue").default
  'NuxtPage': typeof import("../../../../../../node_modules/nuxt/dist/pages/runtime/page").default
  'NoScript': typeof import("../../../../../../node_modules/nuxt/dist/head/runtime/components").NoScript
  'Link': typeof import("../../../../../../node_modules/nuxt/dist/head/runtime/components").Link
  'Base': typeof import("../../../../../../node_modules/nuxt/dist/head/runtime/components").Base
  'Title': typeof import("../../../../../../node_modules/nuxt/dist/head/runtime/components").Title
  'Meta': typeof import("../../../../../../node_modules/nuxt/dist/head/runtime/components").Meta
  'Style': typeof import("../../../../../../node_modules/nuxt/dist/head/runtime/components").Style
  'Head': typeof import("../../../../../../node_modules/nuxt/dist/head/runtime/components").Head
  'Html': typeof import("../../../../../../node_modules/nuxt/dist/head/runtime/components").Html
  'Body': typeof import("../../../../../../node_modules/nuxt/dist/head/runtime/components").Body
  'SchemaOrgDebug': typeof import("@unhead/schema-org/vue").SchemaOrgDebug
  'SchemaOrgArticle': typeof import("@unhead/schema-org/vue").SchemaOrgArticle
  'SchemaOrgBreadcrumb': typeof import("@unhead/schema-org/vue").SchemaOrgBreadcrumb
  'SchemaOrgComment': typeof import("@unhead/schema-org/vue").SchemaOrgComment
  'SchemaOrgEvent': typeof import("@unhead/schema-org/vue").SchemaOrgEvent
  'SchemaOrgFoodEstablishment': typeof import("@unhead/schema-org/vue").SchemaOrgFoodEstablishment
  'SchemaOrgHowTo': typeof import("@unhead/schema-org/vue").SchemaOrgHowTo
  'SchemaOrgImage': typeof import("@unhead/schema-org/vue").SchemaOrgImage
  'SchemaOrgJobPosting': typeof import("@unhead/schema-org/vue").SchemaOrgJobPosting
  'SchemaOrgLocalBusiness': typeof import("@unhead/schema-org/vue").SchemaOrgLocalBusiness
  'SchemaOrgOrganization': typeof import("@unhead/schema-org/vue").SchemaOrgOrganization
  'SchemaOrgPerson': typeof import("@unhead/schema-org/vue").SchemaOrgPerson
  'SchemaOrgProduct': typeof import("@unhead/schema-org/vue").SchemaOrgProduct
  'SchemaOrgQuestion': typeof import("@unhead/schema-org/vue").SchemaOrgQuestion
  'SchemaOrgRecipe': typeof import("@unhead/schema-org/vue").SchemaOrgRecipe
  'SchemaOrgReview': typeof import("@unhead/schema-org/vue").SchemaOrgReview
  'SchemaOrgVideo': typeof import("@unhead/schema-org/vue").SchemaOrgVideo
  'SchemaOrgWebPage': typeof import("@unhead/schema-org/vue").SchemaOrgWebPage
  'SchemaOrgWebSite': typeof import("@unhead/schema-org/vue").SchemaOrgWebSite
  'SchemaOrgMovie': typeof import("@unhead/schema-org/vue").SchemaOrgMovie
  'SchemaOrgCourse': typeof import("@unhead/schema-org/vue").SchemaOrgCourse
  'SchemaOrgItemList': typeof import("@unhead/schema-org/vue").SchemaOrgItemList
  'SchemaOrgBook': typeof import("@unhead/schema-org/vue").SchemaOrgBook
  'SchemaOrgSoftwareApp': typeof import("@unhead/schema-org/vue").SchemaOrgSoftwareApp
  'NuxtIsland': typeof import("../../../../../../node_modules/nuxt/dist/app/components/nuxt-island").default
  'LazyLayoutPageContent': LazyComponent<typeof import("../../../../../../components/layouts/Page/Content.vue").default>
  'LazyLayoutPageFooter': LazyComponent<typeof import("../../../../../../components/layouts/Page/Footer.vue").default>
  'LazyLayoutPageHeader': LazyComponent<typeof import("../../../../../../components/layouts/Page/Header.vue").default>
  'LazyLayoutPageNavbarDropdownThemeSwitcher': LazyComponent<typeof import("../../../../../../components/layouts/Page/NavbarDropdown/ThemeSwitcher.vue").default>
  'LazyLayoutPageNavbarMenuItem': LazyComponent<typeof import("../../../../../../components/layouts/Page/NavbarMenu/Item.vue").default>
  'LazyLayoutPageNavbarMenuWrapper': LazyComponent<typeof import("../../../../../../components/layouts/Page/NavbarMenu/Wrapper.vue").default>
  'LazyLayoutPageSectionTitle': LazyComponent<typeof import("../../../../../../components/layouts/Page/Section/Title.vue").default>
  'LazyLayoutPageSection': LazyComponent<typeof import("../../../../../../components/layouts/Page/Section/index.vue").default>
  'LazyLayoutPageTitle': LazyComponent<typeof import("../../../../../../components/layouts/Page/Title.vue").default>
  'LazyLayoutPageWrapper': LazyComponent<typeof import("../../../../../../components/layouts/Page/Wrapper.vue").default>
  'LazyAwesomeActionSheetGroup': LazyComponent<typeof import("../../../../../../components/awesome/ActionSheet/Group.vue").default>
  'LazyAwesomeActionSheetHeader': LazyComponent<typeof import("../../../../../../components/awesome/ActionSheet/Header.vue").default>
  'LazyAwesomeActionSheetHeaderMessage': LazyComponent<typeof import("../../../../../../components/awesome/ActionSheet/HeaderMessage.vue").default>
  'LazyAwesomeActionSheetHeaderTitle': LazyComponent<typeof import("../../../../../../components/awesome/ActionSheet/HeaderTitle.vue").default>
  'LazyAwesomeActionSheetItem': LazyComponent<typeof import("../../../../../../components/awesome/ActionSheet/Item.vue").default>
  'LazyAwesomeActionSheetItemButton': LazyComponent<typeof import("../../../../../../components/awesome/ActionSheet/ItemButton.vue").default>
  'LazyAwesomeActionSheet': LazyComponent<typeof import("../../../../../../components/awesome/ActionSheet/index.vue").default>
  'LazyAwesomeAlertBanner': LazyComponent<typeof import("../../../../../../components/awesome/AlertBanner.vue").default>
  'LazyAwesomeButton': LazyComponent<typeof import("../../../../../../components/awesome/Button/index.vue").default>
  'LazyAwesomeCardContent': LazyComponent<typeof import("../../../../../../components/awesome/Card/Content.vue").default>
  'LazyAwesomeCardFooter': LazyComponent<typeof import("../../../../../../components/awesome/Card/Footer.vue").default>
  'LazyAwesomeCardTitle': LazyComponent<typeof import("../../../../../../components/awesome/Card/Title.vue").default>
  'LazyAwesomeCard': LazyComponent<typeof import("../../../../../../components/awesome/Card/index.vue").default>
  'LazyAwesomeContentDoc': LazyComponent<typeof import("../../../../../../components/awesome/Content/Doc.vue").default>
  'LazyAwesomeContentRenderer': LazyComponent<typeof import("../../../../../../components/awesome/Content/Renderer.vue").default>
  'LazyAwesomeFloatingMenu': LazyComponent<typeof import("../../../../../../components/awesome/FloatingMenu.vue").default>
  'LazyAwesomeFormSwitch': LazyComponent<typeof import("../../../../../../components/awesome/Form/Switch.vue").default>
  'LazyAwesomeFormTextInput': LazyComponent<typeof import("../../../../../../components/awesome/Form/TextInput.vue").default>
  'LazyAwesomeLink': LazyComponent<typeof import("../../../../../../components/awesome/Link/index.vue").default>
  'LazyAwesomeLoading': LazyComponent<typeof import("../../../../../../components/awesome/Loading.vue").default>
  'LazyAwesomeTab': LazyComponent<typeof import("../../../../../../components/awesome/Tab.vue").default>
  'LazyAwesomeTabs': LazyComponent<typeof import("../../../../../../components/awesome/Tabs.vue").default>
  'LazyAwesomeToast': LazyComponent<typeof import("../../../../../../components/awesome/Toast/index.vue").default>
  'LazyContentDoc': LazyComponent<typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue").default>
  'LazyContentList': LazyComponent<typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue").default>
  'LazyContentNavigation': LazyComponent<typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue").default>
  'LazyContentQuery': LazyComponent<typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue").default>
  'LazyContentRenderer': LazyComponent<typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue").default>
  'LazyContentRendererMarkdown': LazyComponent<typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue").default>
  'LazyContentSlot': LazyComponent<typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue").default>
  'LazyDocumentDrivenEmpty': LazyComponent<typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue").default>
  'LazyDocumentDrivenNotFound': LazyComponent<typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue").default>
  'LazyMarkdown': LazyComponent<typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue").default>
  'LazyProseCode': LazyComponent<typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue").default>
  'LazyProseCodeInline': LazyComponent<typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue").default>
  'LazyProsePre': LazyComponent<typeof import("../../../../../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue").default>
  'LazyProseA': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue").default>
  'LazyProseBlockquote': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue").default>
  'LazyProseEm': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue").default>
  'LazyProseH1': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue").default>
  'LazyProseH2': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue").default>
  'LazyProseH3': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue").default>
  'LazyProseH4': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue").default>
  'LazyProseH5': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue").default>
  'LazyProseH6': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue").default>
  'LazyProseHr': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue").default>
  'LazyProseImg': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue").default>
  'LazyProseLi': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue").default>
  'LazyProseOl': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue").default>
  'LazyProseP': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue").default>
  'LazyProseScript': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue").default>
  'LazyProseStrong': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue").default>
  'LazyProseTable': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue").default>
  'LazyProseTbody': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue").default>
  'LazyProseTd': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue").default>
  'LazyProseTh': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue").default>
  'LazyProseThead': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue").default>
  'LazyProseTr': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue").default>
  'LazyProseUl': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue").default>
  'LazyNuxtWelcome': LazyComponent<typeof import("../../../../../../node_modules/nuxt/dist/app/components/welcome.vue").default>
  'LazyNuxtLayout': LazyComponent<typeof import("../../../../../../node_modules/nuxt/dist/app/components/nuxt-layout").default>
  'LazyNuxtErrorBoundary': LazyComponent<typeof import("../../../../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
  'LazyClientOnly': LazyComponent<typeof import("../../../../../../node_modules/nuxt/dist/app/components/client-only").default>
  'LazyDevOnly': LazyComponent<typeof import("../../../../../../node_modules/nuxt/dist/app/components/dev-only").default>
  'LazyServerPlaceholder': LazyComponent<typeof import("../../../../../../node_modules/nuxt/dist/app/components/server-placeholder").default>
  'LazyNuxtLink': LazyComponent<typeof import("../../../../../../node_modules/nuxt/dist/app/components/nuxt-link").default>
  'LazyNuxtLoadingIndicator': LazyComponent<typeof import("../../../../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
  'LazyNuxtTime': LazyComponent<typeof import("../../../../../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
  'LazyNuxtRouteAnnouncer': LazyComponent<typeof import("../../../../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
  'LazyNuxtImg': LazyComponent<typeof import("../../../../../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg>
  'LazyNuxtPicture': LazyComponent<typeof import("../../../../../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture>
  'LazyHeadlessCombobox': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/combobox/combobox").Combobox>
  'LazyHeadlessComboboxLabel': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/combobox/combobox").ComboboxLabel>
  'LazyHeadlessComboboxButton': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/combobox/combobox").ComboboxButton>
  'LazyHeadlessComboboxInput': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/combobox/combobox").ComboboxInput>
  'LazyHeadlessComboboxOptions': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/combobox/combobox").ComboboxOptions>
  'LazyHeadlessComboboxOption': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/combobox/combobox").ComboboxOption>
  'LazyHeadlessDialog': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/dialog/dialog").Dialog>
  'LazyHeadlessDialogOverlay': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/dialog/dialog").DialogOverlay>
  'LazyHeadlessDialogBackdrop': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/dialog/dialog").DialogBackdrop>
  'LazyHeadlessDialogPanel': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/dialog/dialog").DialogPanel>
  'LazyHeadlessDialogTitle': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/dialog/dialog").DialogTitle>
  'LazyHeadlessDialogDescription': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/dialog/dialog").DialogDescription>
  'LazyHeadlessDisclosure': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/disclosure/disclosure").Disclosure>
  'LazyHeadlessDisclosureButton': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/disclosure/disclosure").DisclosureButton>
  'LazyHeadlessDisclosurePanel': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/disclosure/disclosure").DisclosurePanel>
  'LazyHeadlessFocusTrap': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/focus-trap/focus-trap").FocusTrap>
  'LazyHeadlessListbox': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/listbox/listbox").Listbox>
  'LazyHeadlessListboxLabel': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/listbox/listbox").ListboxLabel>
  'LazyHeadlessListboxButton': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/listbox/listbox").ListboxButton>
  'LazyHeadlessListboxOptions': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/listbox/listbox").ListboxOptions>
  'LazyHeadlessListboxOption': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/listbox/listbox").ListboxOption>
  'LazyHeadlessMenu': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/menu/menu").Menu>
  'LazyHeadlessMenuButton': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/menu/menu").MenuButton>
  'LazyHeadlessMenuItems': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/menu/menu").MenuItems>
  'LazyHeadlessMenuItem': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/menu/menu").MenuItem>
  'LazyHeadlessPopover': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/popover/popover").Popover>
  'LazyHeadlessPopoverButton': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/popover/popover").PopoverButton>
  'LazyHeadlessPopoverOverlay': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/popover/popover").PopoverOverlay>
  'LazyHeadlessPopoverPanel': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/popover/popover").PopoverPanel>
  'LazyHeadlessPopoverGroup': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/popover/popover").PopoverGroup>
  'LazyHeadlessPortal': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/portal/portal").Portal>
  'LazyHeadlessPortalGroup': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/portal/portal").PortalGroup>
  'LazyHeadlessRadioGroup': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/radio-group/radio-group").RadioGroup>
  'LazyHeadlessRadioGroupOption': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/radio-group/radio-group").RadioGroupOption>
  'LazyHeadlessRadioGroupLabel': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/radio-group/radio-group").RadioGroupLabel>
  'LazyHeadlessRadioGroupDescription': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/radio-group/radio-group").RadioGroupDescription>
  'LazyHeadlessSwitchGroup': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/switch/switch").SwitchGroup>
  'LazyHeadlessSwitch': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/switch/switch").Switch>
  'LazyHeadlessSwitchLabel': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/switch/switch").SwitchLabel>
  'LazyHeadlessSwitchDescription': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/switch/switch").SwitchDescription>
  'LazyHeadlessTabGroup': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/tabs/tabs").TabGroup>
  'LazyHeadlessTabList': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/tabs/tabs").TabList>
  'LazyHeadlessTab': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/tabs/tabs").Tab>
  'LazyHeadlessTabPanels': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/tabs/tabs").TabPanels>
  'LazyHeadlessTabPanel': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/tabs/tabs").TabPanel>
  'LazyHeadlessTransitionChild': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/transitions/transition").TransitionChild>
  'LazyHeadlessTransitionRoot': LazyComponent<typeof import("../../../../../../node_modules/@headlessui/vue/dist/components/transitions/transition").TransitionRoot>
  'LazyColorScheme': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue").default>
  'LazyMDC': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue").default>
  'LazyMDCRenderer': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue").default>
  'LazyMDCSlot': LazyComponent<typeof import("../../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue").default>
  'LazyNuxtPage': LazyComponent<typeof import("../../../../../../node_modules/nuxt/dist/pages/runtime/page").default>
  'LazyNoScript': LazyComponent<typeof import("../../../../../../node_modules/nuxt/dist/head/runtime/components").NoScript>
  'LazyLink': LazyComponent<typeof import("../../../../../../node_modules/nuxt/dist/head/runtime/components").Link>
  'LazyBase': LazyComponent<typeof import("../../../../../../node_modules/nuxt/dist/head/runtime/components").Base>
  'LazyTitle': LazyComponent<typeof import("../../../../../../node_modules/nuxt/dist/head/runtime/components").Title>
  'LazyMeta': LazyComponent<typeof import("../../../../../../node_modules/nuxt/dist/head/runtime/components").Meta>
  'LazyStyle': LazyComponent<typeof import("../../../../../../node_modules/nuxt/dist/head/runtime/components").Style>
  'LazyHead': LazyComponent<typeof import("../../../../../../node_modules/nuxt/dist/head/runtime/components").Head>
  'LazyHtml': LazyComponent<typeof import("../../../../../../node_modules/nuxt/dist/head/runtime/components").Html>
  'LazyBody': LazyComponent<typeof import("../../../../../../node_modules/nuxt/dist/head/runtime/components").Body>
  'LazySchemaOrgDebug': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgDebug>
  'LazySchemaOrgArticle': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgArticle>
  'LazySchemaOrgBreadcrumb': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgBreadcrumb>
  'LazySchemaOrgComment': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgComment>
  'LazySchemaOrgEvent': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgEvent>
  'LazySchemaOrgFoodEstablishment': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgFoodEstablishment>
  'LazySchemaOrgHowTo': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgHowTo>
  'LazySchemaOrgImage': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgImage>
  'LazySchemaOrgJobPosting': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgJobPosting>
  'LazySchemaOrgLocalBusiness': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgLocalBusiness>
  'LazySchemaOrgOrganization': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgOrganization>
  'LazySchemaOrgPerson': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgPerson>
  'LazySchemaOrgProduct': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgProduct>
  'LazySchemaOrgQuestion': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgQuestion>
  'LazySchemaOrgRecipe': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgRecipe>
  'LazySchemaOrgReview': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgReview>
  'LazySchemaOrgVideo': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgVideo>
  'LazySchemaOrgWebPage': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgWebPage>
  'LazySchemaOrgWebSite': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgWebSite>
  'LazySchemaOrgMovie': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgMovie>
  'LazySchemaOrgCourse': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgCourse>
  'LazySchemaOrgItemList': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgItemList>
  'LazySchemaOrgBook': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgBook>
  'LazySchemaOrgSoftwareApp': LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgSoftwareApp>
  'LazyNuxtIsland': LazyComponent<typeof import("../../../../../../node_modules/nuxt/dist/app/components/nuxt-island").default>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export {}
