import type { SiteHomeContent } from "../../types";

export const homeContent: SiteHomeContent = {
  copy: {
    creatorFallback: "衣设创作者",
    srTitle: "衣设 POD 印花、定制商品与创意设计开放平台",
    hero: {
      brand: "YISHE",
      eyebrow: "1s.design",
      title: "最大、最具创意的 POD 商品平台。",
      description:
        "在这里发现任何灵感，把它做成服饰、礼物、家居、数码周边，或一次真正属于你的私人定制。",
      primaryAction: { label: "发现创意商品", to: "/products" },
      secondaryAction: { label: "开始私人定制", to: "/design" },
    },
    finder: {
      eyebrow: "Find Your Product",
      title: "先选商品，再让创意落地。",
      description:
        "首页按固定关键词抓取对应商品，结构清晰，也方便后续继续维护更多品类。",
    },
    featureFallbackDescription:
      "从一个作品出发，延展为服饰、礼赠、家居与品牌周边，让创意拥有可被购买、可被定制的商品生命力。",
    runway: {
      eyebrow: "Product Runway",
      title: "任何创意，都能找到合适的商品形态。",
      description:
        "衣设把创作者作品和 POD 商品载体连接起来。你可以为自己定制一件礼物，也可以为品牌策划一整套周边系列。",
    },
    editorialsAriaLabel: "衣设专题",
    journey: {
      ariaLabel: "使用衣设的流程",
      eyebrow: "How it unfolds",
      title: "从灵感到商品，路径清晰。",
    },
    universe: {
      ariaLabel: "按主题探索 POD 商品",
      eyebrow: "POD Universe",
      title: "每一个主题，都有自己的商品宇宙。",
    },
    collection: {
      ariaLabel: "商品系列陈列",
      eyebrow: "Product Gallery",
      title: "更多商品形态，等待被你的创意点亮。",
    },
    feed: {
      eyebrow: "Community Selection",
      title: "来自社区的新灵感",
    },
  },
  fallbackProducts: [
    {
      id: "pod-print-series",
      title: "Botanical Print Capsule",
      description: "适合服饰、帆布包、杯具与家居布艺延展的植物印花系列。",
      category: "POD PRINT",
      type: "印花图案",
      creator: "林小溪",
      likes: 3280,
    },
    {
      id: "custom-gift-set",
      title: "Creator Gift Collection",
      description: "面向节日礼赠、品牌活动与私人纪念的定制商品企划。",
      category: "CUSTOM GIFT",
      type: "定制礼物",
      creator: "Studio W",
      likes: 2560,
    },
    {
      id: "home-textile-art",
      title: "Home Textile Art",
      description: "可延展到抱枕、挂毯、装饰画和软装织物的图案方向。",
      category: "HOME DECOR",
      type: "家居布艺",
      creator: "Artisan Lab",
      likes: 1890,
    },
    {
      id: "streetwear-drop",
      title: "Streetwear Drop",
      description: "适合 T 恤、卫衣、帽衫和潮流周边上新的视觉系列。",
      category: "APPAREL",
      type: "服饰印花",
      creator: "潮研所",
      likes: 5120,
    },
  ],
  categoryTiles: [
    { label: "服饰", keyword: "T恤" },
    { label: "礼赠", keyword: "杯子" },
    { label: "家居", keyword: "抱枕" },
    { label: "数码", keyword: "手机壳" },
    { label: "生活方式", keyword: "帆布包" },
  ],
  productFinderGroups: [
    { key: "mousepad", label: "鼠标垫", keyword: "鼠标垫", hint: "桌面办公 / 游戏周边" },
    { key: "apparel", label: "T 恤", keyword: "T恤", hint: "服饰印花 / 潮流上新" },
    { key: "hoodie", label: "卫衣", keyword: "卫衣", hint: "秋冬服饰 / 社群周边" },
    { key: "drinkware", label: "杯子", keyword: "杯子", hint: "礼赠 / 活动纪念" },
    { key: "digital", label: "手机壳", keyword: "手机壳", hint: "数码配件 / 日常风格" },
    { key: "home", label: "抱枕", keyword: "抱枕", hint: "家居软装 / 空间装饰" },
    { key: "bags", label: "帆布包", keyword: "帆布包", hint: "出行周边 / 品牌物料" },
    { key: "poster", label: "装饰画", keyword: "装饰画", hint: "墙面陈列 / 视觉作品" },
  ],
  modules: [
    {
      key: "mousepad",
      eyebrow: "DESK CULTURE",
      title: "鼠标垫与桌面灵感",
      keyword: "鼠标垫",
      text: "把插画、品牌视觉、游戏梗图或个人签名做成每天都会被看见的桌面装备。",
      href: "/products/鼠标垫",
      limit: 6,
    },
    {
      key: "apparel",
      eyebrow: "WEARABLE IDEAS",
      title: "服饰印花与潮流单品",
      keyword: "T恤",
      text: "T 恤、卫衣、帽衫和更多服饰载体，让创意成为可穿上街的个人表达。",
      href: "/products/T恤",
      limit: 6,
    },
    {
      key: "drinkware",
      eyebrow: "GIFT MOMENTS",
      title: "杯具与礼赠商品",
      keyword: "杯子",
      text: "适合节日、活动、品牌周边与私人纪念，把一句话、一张图变成有温度的礼物。",
      href: "/products/杯子",
      limit: 6,
    },
    {
      key: "home",
      eyebrow: "LIVING OBJECTS",
      title: "家居软装与生活周边",
      keyword: "抱枕",
      text: "抱枕、毯子、装饰画与居家小物，把空间变成作品的延展展厅。",
      href: "/products/抱枕",
      limit: 6,
    },
    {
      key: "digital",
      eyebrow: "DAILY TECH",
      title: "手机壳与数码配件",
      keyword: "手机壳",
      text: "让手机壳、配件与随身物件承载你的风格，也承载品牌的识别度。",
      href: "/products/手机壳",
      limit: 6,
    },
    {
      key: "bags",
      eyebrow: "CITY GOODS",
      title: "帆布包与出行周边",
      keyword: "帆布包",
      text: "把创意从屏幕带到街头，让一只包成为社群、活动和个人态度的移动媒介。",
      href: "/products/帆布包",
      limit: 6,
    },
  ],
  editorials: [
    { title: "PRINT AS PRODUCT", subtitle: "把每一种创意做成商品", href: "/products/印花" },
    { title: "CUSTOM ATELIER", subtitle: "私人定制，从灵感开始", href: "/design" },
    { title: "CREATOR WORKS", subtitle: "发现全球创作者的 POD 灵感", href: "/products" },
  ],
  journeySteps: [
    {
      title: "发现任何创意",
      text: "从插画、图案、潮流字体到品牌视觉，找到能代表你态度的商品灵感。",
    },
    {
      title: "匹配商品载体",
      text: "把创意延展到服饰、杯具、家居、数码配件、礼赠和更多 POD 商品。",
    },
    {
      title: "实现私人定制",
      text: "为个人、品牌、活动或企业礼赠提交需求，让想法进入设计与交付流程。",
    },
  ],
};
