
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T> = DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>> & T

type HydrationStrategies = {
  hydrateOnVisible?: IntersectionObserverInit | true
  hydrateOnIdle?: number | true
  hydrateOnInteraction?: keyof HTMLElementEventMap | Array<keyof HTMLElementEventMap> | true
  hydrateOnMediaQuery?: string
  hydrateAfter?: number
  hydrateWhen?: boolean
  hydrateNever?: true
}
type LazyComponent<T> = DefineComponent<HydrationStrategies, {}, {}, {}, {}, {}, {}, { hydrated: () => void }> & T


export const LayoutPageContent: typeof import("../../../../../components/layouts/Page/Content.vue").default
export const LayoutPageFooter: typeof import("../../../../../components/layouts/Page/Footer.vue").default
export const LayoutPageHeader: typeof import("../../../../../components/layouts/Page/Header.vue").default
export const LayoutPageNavbarDropdownThemeSwitcher: typeof import("../../../../../components/layouts/Page/NavbarDropdown/ThemeSwitcher.vue").default
export const LayoutPageNavbarMenuItem: typeof import("../../../../../components/layouts/Page/NavbarMenu/Item.vue").default
export const LayoutPageNavbarMenuWrapper: typeof import("../../../../../components/layouts/Page/NavbarMenu/Wrapper.vue").default
export const LayoutPageSectionTitle: typeof import("../../../../../components/layouts/Page/Section/Title.vue").default
export const LayoutPageSection: typeof import("../../../../../components/layouts/Page/Section/index.vue").default
export const LayoutPageTitle: typeof import("../../../../../components/layouts/Page/Title.vue").default
export const LayoutPageWrapper: typeof import("../../../../../components/layouts/Page/Wrapper.vue").default
export const AwesomeActionSheetGroup: typeof import("../../../../../components/awesome/ActionSheet/Group.vue").default
export const AwesomeActionSheetHeader: typeof import("../../../../../components/awesome/ActionSheet/Header.vue").default
export const AwesomeActionSheetHeaderMessage: typeof import("../../../../../components/awesome/ActionSheet/HeaderMessage.vue").default
export const AwesomeActionSheetHeaderTitle: typeof import("../../../../../components/awesome/ActionSheet/HeaderTitle.vue").default
export const AwesomeActionSheetItem: typeof import("../../../../../components/awesome/ActionSheet/Item.vue").default
export const AwesomeActionSheetItemButton: typeof import("../../../../../components/awesome/ActionSheet/ItemButton.vue").default
export const AwesomeActionSheet: typeof import("../../../../../components/awesome/ActionSheet/index.vue").default
export const AwesomeAlertBanner: typeof import("../../../../../components/awesome/AlertBanner.vue").default
export const AwesomeButton: typeof import("../../../../../components/awesome/Button/index.vue").default
export const AwesomeCardContent: typeof import("../../../../../components/awesome/Card/Content.vue").default
export const AwesomeCardFooter: typeof import("../../../../../components/awesome/Card/Footer.vue").default
export const AwesomeCardTitle: typeof import("../../../../../components/awesome/Card/Title.vue").default
export const AwesomeCard: typeof import("../../../../../components/awesome/Card/index.vue").default
export const AwesomeContentDoc: typeof import("../../../../../components/awesome/Content/Doc.vue").default
export const AwesomeContentRenderer: typeof import("../../../../../components/awesome/Content/Renderer.vue").default
export const AwesomeFloatingMenu: typeof import("../../../../../components/awesome/FloatingMenu.vue").default
export const AwesomeFormSwitch: typeof import("../../../../../components/awesome/Form/Switch.vue").default
export const AwesomeFormTextInput: typeof import("../../../../../components/awesome/Form/TextInput.vue").default
export const AwesomeLink: typeof import("../../../../../components/awesome/Link/index.vue").default
export const AwesomeLoading: typeof import("../../../../../components/awesome/Loading.vue").default
export const AwesomeTab: typeof import("../../../../../components/awesome/Tab.vue").default
export const AwesomeTabs: typeof import("../../../../../components/awesome/Tabs.vue").default
export const AwesomeToast: typeof import("../../../../../components/awesome/Toast/index.vue").default
export const ContentDoc: typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue").default
export const ContentList: typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue").default
export const ContentNavigation: typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue").default
export const ContentQuery: typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue").default
export const ContentRenderer: typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue").default
export const ContentRendererMarkdown: typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue").default
export const ContentSlot: typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue").default
export const DocumentDrivenEmpty: typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue").default
export const DocumentDrivenNotFound: typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue").default
export const Markdown: typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue").default
export const ProseCode: typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue").default
export const ProseCodeInline: typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue").default
export const ProsePre: typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue").default
export const ProseA: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue").default
export const ProseBlockquote: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue").default
export const ProseEm: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue").default
export const ProseH1: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue").default
export const ProseH2: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue").default
export const ProseH3: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue").default
export const ProseH4: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue").default
export const ProseH5: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue").default
export const ProseH6: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue").default
export const ProseHr: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue").default
export const ProseImg: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue").default
export const ProseLi: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue").default
export const ProseOl: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue").default
export const ProseP: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue").default
export const ProseScript: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue").default
export const ProseStrong: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue").default
export const ProseTable: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue").default
export const ProseTbody: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue").default
export const ProseTd: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue").default
export const ProseTh: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue").default
export const ProseThead: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue").default
export const ProseTr: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue").default
export const ProseUl: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue").default
export const NuxtWelcome: typeof import("../../../../../node_modules/nuxt/dist/app/components/welcome.vue").default
export const NuxtLayout: typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-layout").default
export const NuxtErrorBoundary: typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default
export const ClientOnly: typeof import("../../../../../node_modules/nuxt/dist/app/components/client-only").default
export const DevOnly: typeof import("../../../../../node_modules/nuxt/dist/app/components/dev-only").default
export const ServerPlaceholder: typeof import("../../../../../node_modules/nuxt/dist/app/components/server-placeholder").default
export const NuxtLink: typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-link").default
export const NuxtLoadingIndicator: typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default
export const NuxtTime: typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default
export const NuxtRouteAnnouncer: typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default
export const NuxtImg: typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg
export const NuxtPicture: typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture
export const HeadlessCombobox: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/combobox/combobox").Combobox
export const HeadlessComboboxLabel: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/combobox/combobox").ComboboxLabel
export const HeadlessComboboxButton: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/combobox/combobox").ComboboxButton
export const HeadlessComboboxInput: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/combobox/combobox").ComboboxInput
export const HeadlessComboboxOptions: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/combobox/combobox").ComboboxOptions
export const HeadlessComboboxOption: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/combobox/combobox").ComboboxOption
export const HeadlessDialog: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/dialog/dialog").Dialog
export const HeadlessDialogOverlay: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/dialog/dialog").DialogOverlay
export const HeadlessDialogBackdrop: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/dialog/dialog").DialogBackdrop
export const HeadlessDialogPanel: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/dialog/dialog").DialogPanel
export const HeadlessDialogTitle: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/dialog/dialog").DialogTitle
export const HeadlessDialogDescription: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/dialog/dialog").DialogDescription
export const HeadlessDisclosure: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/disclosure/disclosure").Disclosure
export const HeadlessDisclosureButton: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/disclosure/disclosure").DisclosureButton
export const HeadlessDisclosurePanel: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/disclosure/disclosure").DisclosurePanel
export const HeadlessFocusTrap: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/focus-trap/focus-trap").FocusTrap
export const HeadlessListbox: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/listbox/listbox").Listbox
export const HeadlessListboxLabel: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/listbox/listbox").ListboxLabel
export const HeadlessListboxButton: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/listbox/listbox").ListboxButton
export const HeadlessListboxOptions: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/listbox/listbox").ListboxOptions
export const HeadlessListboxOption: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/listbox/listbox").ListboxOption
export const HeadlessMenu: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/menu/menu").Menu
export const HeadlessMenuButton: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/menu/menu").MenuButton
export const HeadlessMenuItems: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/menu/menu").MenuItems
export const HeadlessMenuItem: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/menu/menu").MenuItem
export const HeadlessPopover: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/popover/popover").Popover
export const HeadlessPopoverButton: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/popover/popover").PopoverButton
export const HeadlessPopoverOverlay: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/popover/popover").PopoverOverlay
export const HeadlessPopoverPanel: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/popover/popover").PopoverPanel
export const HeadlessPopoverGroup: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/popover/popover").PopoverGroup
export const HeadlessPortal: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/portal/portal").Portal
export const HeadlessPortalGroup: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/portal/portal").PortalGroup
export const HeadlessRadioGroup: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/radio-group/radio-group").RadioGroup
export const HeadlessRadioGroupOption: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/radio-group/radio-group").RadioGroupOption
export const HeadlessRadioGroupLabel: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/radio-group/radio-group").RadioGroupLabel
export const HeadlessRadioGroupDescription: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/radio-group/radio-group").RadioGroupDescription
export const HeadlessSwitchGroup: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/switch/switch").SwitchGroup
export const HeadlessSwitch: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/switch/switch").Switch
export const HeadlessSwitchLabel: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/switch/switch").SwitchLabel
export const HeadlessSwitchDescription: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/switch/switch").SwitchDescription
export const HeadlessTabGroup: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/tabs/tabs").TabGroup
export const HeadlessTabList: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/tabs/tabs").TabList
export const HeadlessTab: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/tabs/tabs").Tab
export const HeadlessTabPanels: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/tabs/tabs").TabPanels
export const HeadlessTabPanel: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/tabs/tabs").TabPanel
export const HeadlessTransitionChild: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/transitions/transition").TransitionChild
export const HeadlessTransitionRoot: typeof import("../../../../../node_modules/@headlessui/vue/dist/components/transitions/transition").TransitionRoot
export const ColorScheme: typeof import("../../../../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue").default
export const MDC: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue").default
export const MDCRenderer: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue").default
export const MDCSlot: typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue").default
export const NuxtPage: typeof import("../../../../../node_modules/nuxt/dist/pages/runtime/page").default
export const NoScript: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components").NoScript
export const Link: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components").Link
export const Base: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components").Base
export const Title: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components").Title
export const Meta: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components").Meta
export const Style: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components").Style
export const Head: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components").Head
export const Html: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components").Html
export const Body: typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components").Body
export const SchemaOrgDebug: typeof import("@unhead/schema-org/vue").SchemaOrgDebug
export const SchemaOrgArticle: typeof import("@unhead/schema-org/vue").SchemaOrgArticle
export const SchemaOrgBreadcrumb: typeof import("@unhead/schema-org/vue").SchemaOrgBreadcrumb
export const SchemaOrgComment: typeof import("@unhead/schema-org/vue").SchemaOrgComment
export const SchemaOrgEvent: typeof import("@unhead/schema-org/vue").SchemaOrgEvent
export const SchemaOrgFoodEstablishment: typeof import("@unhead/schema-org/vue").SchemaOrgFoodEstablishment
export const SchemaOrgHowTo: typeof import("@unhead/schema-org/vue").SchemaOrgHowTo
export const SchemaOrgImage: typeof import("@unhead/schema-org/vue").SchemaOrgImage
export const SchemaOrgJobPosting: typeof import("@unhead/schema-org/vue").SchemaOrgJobPosting
export const SchemaOrgLocalBusiness: typeof import("@unhead/schema-org/vue").SchemaOrgLocalBusiness
export const SchemaOrgOrganization: typeof import("@unhead/schema-org/vue").SchemaOrgOrganization
export const SchemaOrgPerson: typeof import("@unhead/schema-org/vue").SchemaOrgPerson
export const SchemaOrgProduct: typeof import("@unhead/schema-org/vue").SchemaOrgProduct
export const SchemaOrgQuestion: typeof import("@unhead/schema-org/vue").SchemaOrgQuestion
export const SchemaOrgRecipe: typeof import("@unhead/schema-org/vue").SchemaOrgRecipe
export const SchemaOrgReview: typeof import("@unhead/schema-org/vue").SchemaOrgReview
export const SchemaOrgVideo: typeof import("@unhead/schema-org/vue").SchemaOrgVideo
export const SchemaOrgWebPage: typeof import("@unhead/schema-org/vue").SchemaOrgWebPage
export const SchemaOrgWebSite: typeof import("@unhead/schema-org/vue").SchemaOrgWebSite
export const SchemaOrgMovie: typeof import("@unhead/schema-org/vue").SchemaOrgMovie
export const SchemaOrgCourse: typeof import("@unhead/schema-org/vue").SchemaOrgCourse
export const SchemaOrgItemList: typeof import("@unhead/schema-org/vue").SchemaOrgItemList
export const SchemaOrgBook: typeof import("@unhead/schema-org/vue").SchemaOrgBook
export const SchemaOrgSoftwareApp: typeof import("@unhead/schema-org/vue").SchemaOrgSoftwareApp
export const NuxtIsland: typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-island").default
export const LazyLayoutPageContent: LazyComponent<typeof import("../../../../../components/layouts/Page/Content.vue").default>
export const LazyLayoutPageFooter: LazyComponent<typeof import("../../../../../components/layouts/Page/Footer.vue").default>
export const LazyLayoutPageHeader: LazyComponent<typeof import("../../../../../components/layouts/Page/Header.vue").default>
export const LazyLayoutPageNavbarDropdownThemeSwitcher: LazyComponent<typeof import("../../../../../components/layouts/Page/NavbarDropdown/ThemeSwitcher.vue").default>
export const LazyLayoutPageNavbarMenuItem: LazyComponent<typeof import("../../../../../components/layouts/Page/NavbarMenu/Item.vue").default>
export const LazyLayoutPageNavbarMenuWrapper: LazyComponent<typeof import("../../../../../components/layouts/Page/NavbarMenu/Wrapper.vue").default>
export const LazyLayoutPageSectionTitle: LazyComponent<typeof import("../../../../../components/layouts/Page/Section/Title.vue").default>
export const LazyLayoutPageSection: LazyComponent<typeof import("../../../../../components/layouts/Page/Section/index.vue").default>
export const LazyLayoutPageTitle: LazyComponent<typeof import("../../../../../components/layouts/Page/Title.vue").default>
export const LazyLayoutPageWrapper: LazyComponent<typeof import("../../../../../components/layouts/Page/Wrapper.vue").default>
export const LazyAwesomeActionSheetGroup: LazyComponent<typeof import("../../../../../components/awesome/ActionSheet/Group.vue").default>
export const LazyAwesomeActionSheetHeader: LazyComponent<typeof import("../../../../../components/awesome/ActionSheet/Header.vue").default>
export const LazyAwesomeActionSheetHeaderMessage: LazyComponent<typeof import("../../../../../components/awesome/ActionSheet/HeaderMessage.vue").default>
export const LazyAwesomeActionSheetHeaderTitle: LazyComponent<typeof import("../../../../../components/awesome/ActionSheet/HeaderTitle.vue").default>
export const LazyAwesomeActionSheetItem: LazyComponent<typeof import("../../../../../components/awesome/ActionSheet/Item.vue").default>
export const LazyAwesomeActionSheetItemButton: LazyComponent<typeof import("../../../../../components/awesome/ActionSheet/ItemButton.vue").default>
export const LazyAwesomeActionSheet: LazyComponent<typeof import("../../../../../components/awesome/ActionSheet/index.vue").default>
export const LazyAwesomeAlertBanner: LazyComponent<typeof import("../../../../../components/awesome/AlertBanner.vue").default>
export const LazyAwesomeButton: LazyComponent<typeof import("../../../../../components/awesome/Button/index.vue").default>
export const LazyAwesomeCardContent: LazyComponent<typeof import("../../../../../components/awesome/Card/Content.vue").default>
export const LazyAwesomeCardFooter: LazyComponent<typeof import("../../../../../components/awesome/Card/Footer.vue").default>
export const LazyAwesomeCardTitle: LazyComponent<typeof import("../../../../../components/awesome/Card/Title.vue").default>
export const LazyAwesomeCard: LazyComponent<typeof import("../../../../../components/awesome/Card/index.vue").default>
export const LazyAwesomeContentDoc: LazyComponent<typeof import("../../../../../components/awesome/Content/Doc.vue").default>
export const LazyAwesomeContentRenderer: LazyComponent<typeof import("../../../../../components/awesome/Content/Renderer.vue").default>
export const LazyAwesomeFloatingMenu: LazyComponent<typeof import("../../../../../components/awesome/FloatingMenu.vue").default>
export const LazyAwesomeFormSwitch: LazyComponent<typeof import("../../../../../components/awesome/Form/Switch.vue").default>
export const LazyAwesomeFormTextInput: LazyComponent<typeof import("../../../../../components/awesome/Form/TextInput.vue").default>
export const LazyAwesomeLink: LazyComponent<typeof import("../../../../../components/awesome/Link/index.vue").default>
export const LazyAwesomeLoading: LazyComponent<typeof import("../../../../../components/awesome/Loading.vue").default>
export const LazyAwesomeTab: LazyComponent<typeof import("../../../../../components/awesome/Tab.vue").default>
export const LazyAwesomeTabs: LazyComponent<typeof import("../../../../../components/awesome/Tabs.vue").default>
export const LazyAwesomeToast: LazyComponent<typeof import("../../../../../components/awesome/Toast/index.vue").default>
export const LazyContentDoc: LazyComponent<typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentDoc.vue").default>
export const LazyContentList: LazyComponent<typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentList.vue").default>
export const LazyContentNavigation: LazyComponent<typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentNavigation.vue").default>
export const LazyContentQuery: LazyComponent<typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentQuery.vue").default>
export const LazyContentRenderer: LazyComponent<typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentRenderer.vue").default>
export const LazyContentRendererMarkdown: LazyComponent<typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentRendererMarkdown.vue").default>
export const LazyContentSlot: LazyComponent<typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/ContentSlot.vue").default>
export const LazyDocumentDrivenEmpty: LazyComponent<typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenEmpty.vue").default>
export const LazyDocumentDrivenNotFound: LazyComponent<typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/DocumentDrivenNotFound.vue").default>
export const LazyMarkdown: LazyComponent<typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/Markdown.vue").default>
export const LazyProseCode: LazyComponent<typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCode.vue").default>
export const LazyProseCodeInline: LazyComponent<typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProseCodeInline.vue").default>
export const LazyProsePre: LazyComponent<typeof import("../../../../../node_modules/@nuxt/content/dist/runtime/components/Prose/ProsePre.vue").default>
export const LazyProseA: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseA.vue").default>
export const LazyProseBlockquote: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseBlockquote.vue").default>
export const LazyProseEm: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseEm.vue").default>
export const LazyProseH1: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH1.vue").default>
export const LazyProseH2: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH2.vue").default>
export const LazyProseH3: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH3.vue").default>
export const LazyProseH4: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH4.vue").default>
export const LazyProseH5: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH5.vue").default>
export const LazyProseH6: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseH6.vue").default>
export const LazyProseHr: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseHr.vue").default>
export const LazyProseImg: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseImg.vue").default>
export const LazyProseLi: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseLi.vue").default>
export const LazyProseOl: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseOl.vue").default>
export const LazyProseP: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseP.vue").default>
export const LazyProseScript: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseScript.vue").default>
export const LazyProseStrong: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseStrong.vue").default>
export const LazyProseTable: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTable.vue").default>
export const LazyProseTbody: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTbody.vue").default>
export const LazyProseTd: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTd.vue").default>
export const LazyProseTh: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTh.vue").default>
export const LazyProseThead: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseThead.vue").default>
export const LazyProseTr: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseTr.vue").default>
export const LazyProseUl: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/prose/ProseUl.vue").default>
export const LazyNuxtWelcome: LazyComponent<typeof import("../../../../../node_modules/nuxt/dist/app/components/welcome.vue").default>
export const LazyNuxtLayout: LazyComponent<typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-layout").default>
export const LazyNuxtErrorBoundary: LazyComponent<typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-error-boundary.vue").default>
export const LazyClientOnly: LazyComponent<typeof import("../../../../../node_modules/nuxt/dist/app/components/client-only").default>
export const LazyDevOnly: LazyComponent<typeof import("../../../../../node_modules/nuxt/dist/app/components/dev-only").default>
export const LazyServerPlaceholder: LazyComponent<typeof import("../../../../../node_modules/nuxt/dist/app/components/server-placeholder").default>
export const LazyNuxtLink: LazyComponent<typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-link").default>
export const LazyNuxtLoadingIndicator: LazyComponent<typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-loading-indicator").default>
export const LazyNuxtTime: LazyComponent<typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-time.vue").default>
export const LazyNuxtRouteAnnouncer: LazyComponent<typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-route-announcer").default>
export const LazyNuxtImg: LazyComponent<typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtImg>
export const LazyNuxtPicture: LazyComponent<typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-stubs").NuxtPicture>
export const LazyHeadlessCombobox: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/combobox/combobox").Combobox>
export const LazyHeadlessComboboxLabel: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/combobox/combobox").ComboboxLabel>
export const LazyHeadlessComboboxButton: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/combobox/combobox").ComboboxButton>
export const LazyHeadlessComboboxInput: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/combobox/combobox").ComboboxInput>
export const LazyHeadlessComboboxOptions: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/combobox/combobox").ComboboxOptions>
export const LazyHeadlessComboboxOption: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/combobox/combobox").ComboboxOption>
export const LazyHeadlessDialog: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/dialog/dialog").Dialog>
export const LazyHeadlessDialogOverlay: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/dialog/dialog").DialogOverlay>
export const LazyHeadlessDialogBackdrop: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/dialog/dialog").DialogBackdrop>
export const LazyHeadlessDialogPanel: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/dialog/dialog").DialogPanel>
export const LazyHeadlessDialogTitle: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/dialog/dialog").DialogTitle>
export const LazyHeadlessDialogDescription: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/dialog/dialog").DialogDescription>
export const LazyHeadlessDisclosure: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/disclosure/disclosure").Disclosure>
export const LazyHeadlessDisclosureButton: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/disclosure/disclosure").DisclosureButton>
export const LazyHeadlessDisclosurePanel: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/disclosure/disclosure").DisclosurePanel>
export const LazyHeadlessFocusTrap: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/focus-trap/focus-trap").FocusTrap>
export const LazyHeadlessListbox: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/listbox/listbox").Listbox>
export const LazyHeadlessListboxLabel: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/listbox/listbox").ListboxLabel>
export const LazyHeadlessListboxButton: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/listbox/listbox").ListboxButton>
export const LazyHeadlessListboxOptions: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/listbox/listbox").ListboxOptions>
export const LazyHeadlessListboxOption: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/listbox/listbox").ListboxOption>
export const LazyHeadlessMenu: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/menu/menu").Menu>
export const LazyHeadlessMenuButton: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/menu/menu").MenuButton>
export const LazyHeadlessMenuItems: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/menu/menu").MenuItems>
export const LazyHeadlessMenuItem: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/menu/menu").MenuItem>
export const LazyHeadlessPopover: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/popover/popover").Popover>
export const LazyHeadlessPopoverButton: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/popover/popover").PopoverButton>
export const LazyHeadlessPopoverOverlay: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/popover/popover").PopoverOverlay>
export const LazyHeadlessPopoverPanel: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/popover/popover").PopoverPanel>
export const LazyHeadlessPopoverGroup: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/popover/popover").PopoverGroup>
export const LazyHeadlessPortal: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/portal/portal").Portal>
export const LazyHeadlessPortalGroup: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/portal/portal").PortalGroup>
export const LazyHeadlessRadioGroup: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/radio-group/radio-group").RadioGroup>
export const LazyHeadlessRadioGroupOption: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/radio-group/radio-group").RadioGroupOption>
export const LazyHeadlessRadioGroupLabel: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/radio-group/radio-group").RadioGroupLabel>
export const LazyHeadlessRadioGroupDescription: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/radio-group/radio-group").RadioGroupDescription>
export const LazyHeadlessSwitchGroup: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/switch/switch").SwitchGroup>
export const LazyHeadlessSwitch: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/switch/switch").Switch>
export const LazyHeadlessSwitchLabel: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/switch/switch").SwitchLabel>
export const LazyHeadlessSwitchDescription: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/switch/switch").SwitchDescription>
export const LazyHeadlessTabGroup: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/tabs/tabs").TabGroup>
export const LazyHeadlessTabList: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/tabs/tabs").TabList>
export const LazyHeadlessTab: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/tabs/tabs").Tab>
export const LazyHeadlessTabPanels: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/tabs/tabs").TabPanels>
export const LazyHeadlessTabPanel: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/tabs/tabs").TabPanel>
export const LazyHeadlessTransitionChild: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/transitions/transition").TransitionChild>
export const LazyHeadlessTransitionRoot: LazyComponent<typeof import("../../../../../node_modules/@headlessui/vue/dist/components/transitions/transition").TransitionRoot>
export const LazyColorScheme: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue").default>
export const LazyMDC: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDC.vue").default>
export const LazyMDCRenderer: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCRenderer.vue").default>
export const LazyMDCSlot: LazyComponent<typeof import("../../../../../node_modules/@nuxtjs/mdc/dist/runtime/components/MDCSlot.vue").default>
export const LazyNuxtPage: LazyComponent<typeof import("../../../../../node_modules/nuxt/dist/pages/runtime/page").default>
export const LazyNoScript: LazyComponent<typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components").NoScript>
export const LazyLink: LazyComponent<typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components").Link>
export const LazyBase: LazyComponent<typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components").Base>
export const LazyTitle: LazyComponent<typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components").Title>
export const LazyMeta: LazyComponent<typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components").Meta>
export const LazyStyle: LazyComponent<typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components").Style>
export const LazyHead: LazyComponent<typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components").Head>
export const LazyHtml: LazyComponent<typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components").Html>
export const LazyBody: LazyComponent<typeof import("../../../../../node_modules/nuxt/dist/head/runtime/components").Body>
export const LazySchemaOrgDebug: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgDebug>
export const LazySchemaOrgArticle: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgArticle>
export const LazySchemaOrgBreadcrumb: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgBreadcrumb>
export const LazySchemaOrgComment: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgComment>
export const LazySchemaOrgEvent: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgEvent>
export const LazySchemaOrgFoodEstablishment: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgFoodEstablishment>
export const LazySchemaOrgHowTo: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgHowTo>
export const LazySchemaOrgImage: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgImage>
export const LazySchemaOrgJobPosting: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgJobPosting>
export const LazySchemaOrgLocalBusiness: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgLocalBusiness>
export const LazySchemaOrgOrganization: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgOrganization>
export const LazySchemaOrgPerson: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgPerson>
export const LazySchemaOrgProduct: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgProduct>
export const LazySchemaOrgQuestion: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgQuestion>
export const LazySchemaOrgRecipe: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgRecipe>
export const LazySchemaOrgReview: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgReview>
export const LazySchemaOrgVideo: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgVideo>
export const LazySchemaOrgWebPage: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgWebPage>
export const LazySchemaOrgWebSite: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgWebSite>
export const LazySchemaOrgMovie: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgMovie>
export const LazySchemaOrgCourse: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgCourse>
export const LazySchemaOrgItemList: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgItemList>
export const LazySchemaOrgBook: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgBook>
export const LazySchemaOrgSoftwareApp: LazyComponent<typeof import("@unhead/schema-org/vue").SchemaOrgSoftwareApp>
export const LazyNuxtIsland: LazyComponent<typeof import("../../../../../node_modules/nuxt/dist/app/components/nuxt-island").default>

export const componentNames: string[]
